exports.requestStatus = {
  PENDING: 1,
  ORDERING_REQUESTED_HARDWARE: 2,
  REQUESTED_HARDWARE_AVALIABLE: 3,
  REQUESTED_HARDWARE_NOT_AVALIABLE: 4,
  ORDERED: 5,
  READY: 6,
  SCHEDULED: 7,
  DONE_FOR_REVIEW: 8,
  AWAITING_FOR_ACCOUNTING: 9,
  DONE_FROM_ACCOUNTANT: 10,
  DONE_WITH_COMMENT: 11,
  CANCELED: 12,
};
